# Generated by Django 5.0.6 on 2024-07-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort_info',
            fields=[
                ('resort_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('radius', models.FloatField(default=0)),
                ('resortHomeUrl', models.CharField(max_length=255)),
                ('url_naver', models.CharField(max_length=255)),
                ('url_webcam', models.CharField(max_length=255)),
                ('url_slope', models.CharField(max_length=255)),
                ('url_bus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reset_point',
            fields=[
                ('reset_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('radius', models.FloatField(default=0)),
                ('resort_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info')),
            ],
        ),
        migrations.CreateModel(
            name='Respawn_point',
            fields=[
                ('reset_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('radius', models.FloatField(default=0)),
                ('resort_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info')),
            ],
        ),
        migrations.CreateModel(
            name='Slope_info',
            fields=[
                ('slope_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('radius', models.FloatField(default=0)),
                ('slope_avg', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('resort_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info')),
            ],
        ),
    ]
