# Generated by Django 5.0.6 on 2024-07-01 13:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset_point',
            fields=[
                ('reset_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resort_info',
            fields=[
                ('resort_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius', models.FloatField(default=0)),
                ('resortHomeUrl', models.CharField(max_length=255)),
                ('url_naver', models.CharField(max_length=255)),
                ('url_webcam', models.CharField(max_length=255)),
                ('url_slope', models.CharField(max_length=255)),
                ('url_bus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Respawn_point',
            fields=[
                ('reset_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slope_info',
            fields=[
                ('slope_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius', models.FloatField(default=0)),
                ('slope_avg', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
