# Generated by Django 5.0.6 on 2024-07-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_app', '0002_reset_point_resort_info_respawn_point_slope_info'),
        ('user_app', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResortInfo',
        ),
        migrations.AddField(
            model_name='reset_point',
            name='resort_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info'),
        ),
        migrations.AddField(
            model_name='respawn_point',
            name='resort_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info'),
        ),
        migrations.AddField(
            model_name='slope_info',
            name='resort_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info'),
        ),
    ]
