# Generated by Django 5.0.6 on 2024-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_record',
            fields=[
                ('ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Slope_pass_temp',
            fields=[
                ('slope_pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
