# Generated by Django 5.0.6 on 2024-07-01 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranking_app', '0002_initial'),
        ('resort_app', '0002_reset_point_resort_info_respawn_point_slope_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking_record',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slope_pass_temp',
            name='slope_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_app.slope_info'),
        ),
        migrations.AddField(
            model_name='slope_pass_temp',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
