# Generated by Django 5.0.6 on 2024-07-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resort_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew_info',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(max_length=255)),
                ('crew_logo_url', models.CharField(max_length=255)),
                ('iskusbf', models.BooleanField(default=False)),
                ('notice', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('base_resort_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info')),
            ],
        ),
    ]
