# Generated by Django 5.0.6 on 2024-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew_info',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(max_length=255)),
                ('crew_logo_url', models.CharField(max_length=255)),
                ('iskusbf', models.BooleanField(default=False)),
                ('notice', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
