# Generated by Django 5.0.6 on 2024-07-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew_app', '0001_initial'),
        ('resort_app', '0002_reset_point_resort_info_respawn_point_slope_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew_info',
            name='base_resort_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_app.resort_info'),
        ),
    ]
